In [1]:
from models import DiT_models
import torch

latent_size = 256//8
device= 'cuda:2'
model = DiT_models['DiT-L/2-Text'](
        input_size=latent_size,
        # num_classes=args.num_classes
).to(device)
model.load_state_dict(torch.load('/workspace/austin/huchudle/results/008-DiT-L-2-Text/checkpoints/0333300.pt', map_location=device)['model'])

model.eval()


DiT(
  (x_embedder): PatchEmbed(
    (proj): Conv2d(5, 1024, kernel_size=(2, 2), stride=(2, 2))
    (norm): Identity()
  )
  (t_embedder): TimestepEmbedder(
    (mlp): Sequential(
      (0): Linear(in_features=256, out_features=1024, bias=True)
      (1): SiLU()
      (2): Linear(in_features=1024, out_features=1024, bias=True)
    )
  )
  (text_encoder): CLIPTextModel(
    (text_model): CLIPTextTransformer(
      (embeddings): CLIPTextEmbeddings(
        (token_embedding): Embedding(49408, 1024)
        (position_embedding): Embedding(77, 1024)
      )
      (encoder): CLIPEncoder(
        (layers): ModuleList(
          (0-22): 23 x CLIPEncoderLayer(
            (self_attn): CLIPAttention(
              (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
              (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
              (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
              (out_proj): Linear(in_features=1024, out_features

In [3]:
tokens = torch.zeros(1, 77).to(device, torch.int64) + 7788
orig=model.text_embedder("", train=False, token=tokens)

In [5]:
model.remove_pos_emb(device)
after = model.text_embedder("", train=False, token=tokens)

In [6]:
after[0, 0], after[0, 1]

(tensor([-1.0480,  0.0387, -1.9429,  ...,  0.0639,  2.0870, -0.5573],
        device='cuda:2', grad_fn=<SelectBackward0>),
 tensor([-1.0480,  0.0387, -1.9429,  ...,  0.0639,  2.0870, -0.5573],
        device='cuda:2', grad_fn=<SelectBackward0>))

In [4]:
orig[0, 0], orig[0, 1]

(tensor([-1.0117, -0.0769, -1.7586,  ...,  0.0954,  1.0750, -0.0861],
        device='cuda:2'),
 tensor([-0.8220,  0.3744, -2.3053,  ...,  0.3900,  0.9271, -0.2098],
        device='cuda:2'))

In [10]:
after.shape, orig.shape

(torch.Size([1, 77, 1024]), torch.Size([1, 77, 1024]))